name: Confirm Flaky Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout IDoFT repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Clone DataflowTemplates repository
      run: |
        git clone https://github.com/GoogleCloudPlatform/DataflowTemplates.git
        cd DataflowTemplates
        git checkout main # Ensure you are on the correct branch
        mvn clean install -DskipTests -pl . -am

    - name: Run NonDex to confirm flaky test
      working-directory: DataflowTemplates
      run: |
        mvn -pl . edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn
    - name: Save NonDex logs
      uses: actions/upload-artifact@v2
      with:
        name: nondex-logs
        path: ~/.
