name: Confirm Flaky Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install NonDex plugin
      run: |
        mvn edu.illinois:nondex-maven-plugin:2.1.1:setup

    - name: Run NonDex to confirm flaky test
      run: |
        mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn

    - name: Save NonDex logs
      uses: actions/upload-artifact@v2
      with:
        name: nondex-logs
        path: ~/.nondex
